- name: mysql configuration
  hosts: mysql
  become: yes
  vars:
    mysql_root_password: ExpenseApp@1
    login_host: mysql.daws81s.online
  tasks:
  - name: install MySQL Server
    ansible.builtin.package:
      name: mysql-server
      state: present

  - name: start mysql server
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes

  # check password is already setup or not
  - name: check DB connection
    community.mysql.mysql_info:
      login_user: root
      login_password: "{{ mysql_root_password }}"
      login_host: "{{ login_host }}"
      filter: version
    ignore_errors: yes
    register: mysql_connection_output

  - name: print output
    ansible.builtin.debug:
      msg: "{{ mysql_connection_output }}"